{% set version = "0.3.0" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
  sha256: 0ecccfe5a09b25b6640afca12de62062bdb60ed2712d6c16cc47fc1ba1e851ac

build:
  number: 2
  skip: true        # [win and not py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - symengine     0.3.0
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - cython
    - setuptools
  run:
    - symengine     0.3.0
    - python
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine
  commands:
    - python -c $'import symengine;\nif not symengine.test():\n raise Exception("Tests failed")'    # [unix]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: 'Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
