# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython2.7
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.6
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oxV0/l+XEq/7WRSCqI+KsJIZj46yiQo/wK5EEOxw/5FlCjOtoUlpeiDxpDVfY2EcyNVw4OhAp+dCtU78T5Xk+0MyXsjFBY4/wEq45K407WEYNT4P3eo7gXFOxutzc2zceIH87W3TuWIxZrPfuMuqFmrkbvlA4YaHoSLAVWv7k8Vz6tu4IUb6YSPF6rXFq0XK2IFI/dYDvQcj1Do/sJQmT1cUMMazFPbAxQzLVj4H0i9t8Z3UVqi7CXxeW7fgIAbI04yzjDoDXM8IN4w3UYxtEx5GF+E+FyJJrwsg2vKQGmavNEvMCPQWWdiJEowIyDMnbe9164hLCqeHbZCgIKz2biR7L9Kc7i/OL+2nsXmvMQthcDj6Uqe10LjguqiKjvKAp/GWcg+MgX+9ArdTk4N/fVJ0auPb7gyRJJFM0ivpB2NuOGaOGAHRw6Hvsr33qBHgL3ThNnPmgKa40En66N905l3QAIDDEYvaGlInD8q1qCQU43Z5qSa9Xt0FGMJ0vQbnxVQ/pFkgx1qXo+DJZ0R69BZ1QQIXLAzJ2FrZGnjotajiMGUYOuIL3/UylAv3p7XaKa2DSPXcMeO8Yy0W0+1FqKqxmpt9Rp4GfehccVwkvqeRXfYBFDeBE7/Uw42j5FMjaeJQUY6i/ZOq+fzoUF3eA+1srh+6JQXl5w6mv1pLhy0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
